#ifndef BASEWALLPAPERPLUGIN_GLOBAL_H
#define BASEWALLPAPERPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(BASEWALLPAPERPLUGIN_LIBRARY)
#  define BASEWALLPAPERPLUGIN_EXPORT Q_DECL_EXPORT
#else
#  define BASEWALLPAPERPLUGIN_EXPORT Q_DECL_IMPORT
#endif

#endif // BASEWALLPAPERPLUGIN_GLOBAL_H
