/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n4.4.3-4-gd585a0a1cc-20230326"
#endif /* AVUTIL_FFVERSION_H */
